version: '3.1' 
services: 
    nginx: 
      image: nginx 
      restart: always 
      ports: 
        - 3000:80
      volumes: 
        - "./conf.d/default.conf:/etc/nginx/conf.d/default.conf"
        - "./dist:/var/www/html"
        #- ./static/:/static/
    